AppCoder/urls.py
from django.urls import *
from AppCoder.views import *
from django.contrib.auth.views import *
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns = [
    path("", LoginView.as_view(), name="login"),
    path('logout/', custom_logout, name='logout'),  #  personalizada
    path('crear_perfil/', login_required(UserProfileCreateView.as_view()), name='crear_perfil'),
    path('detalle_perfil/<int:user_id>/', detalle_perfil, name='detalle_perfil'),
    path("padre/", inicio, name="inicio"),
    path("cliente/", cliente, name="Cliente"),
    path("formCliente/", formCliente, name="formCliente"),
    path('formProducto/', formProducto, name='formProducto'),
    path('producto/<int:producto_id>/', detalle_producto, name='detalle_producto'),
    path('lista_productos/', lista_productos, name='lista_productos'),
    path('eliminar_cliente/<int:cliente_id>/', eliminar_cliente, name='eliminar_cliente'),
    path('clientes/', lista_clientes, name='lista_clientes'),
    path('editar_cliente/<int:cliente_id>/', editar_cliente, name='editar_cliente'),
    path('cliente/<int:cliente_id>/', detalle_cliente, name='detalle_cliente'),
    path('editar_producto/<int:producto_id>/', editar_producto, name='editar_producto'),
    path('eliminar_producto/<int:producto_id>/', eliminar_producto, name='eliminar_producto'),
        # URLs para Movimientos de Stock
    path('detalle_movimiento_stock/<int:movimiento_stock_id>/', detalle_movimiento_stock, name='detalle_movimiento_stock'),
    path('movimientos_stock/', lista_movimientos_stock, name='lista_movimientos_stock'),
    path('crear_movimiento_stock/', crear_movimiento_stock, name='crear_movimiento_stock'),
    path('editar_movimiento_stock/<int:movimiento_stock_id>/', editar_movimiento_stock, name='editar_movimiento_stock'),
    path('eliminar_movimiento_stock/<int:movimiento_stock_id>/', eliminar_movimiento_stock, name='eliminar_movimiento_stock'),
    # URLs para Depósitos
    path('depositos/', lista_depositos, name='lista_depositos'),
    path('crear_deposito/', crear_deposito, name='crear_deposito'),
    path('editar_deposito/<int:deposito_id>/', editar_deposito, name='editar_deposito'),
    path('eliminar_deposito/<int:deposito_id>/', eliminar_deposito, name='eliminar_deposito'),
    path('tipos_movimiento/', lista_tipos_movimiento, name='lista_tipos_movimiento'),
    path('crear_tipo_movimiento/', crear_tipo_movimiento, name='crear_tipo_movimiento'),
   

    

]

ProyectoCoder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('AppCoder/',include("AppCoder.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppCoder/models.py
from django.db import models
import uuid
from django.dispatch import receiver
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User


# Create your models here.

class Cliente(models.Model):
    nombre=models.CharField(max_length=30)
    apellido=models.CharField(max_length=30)
    cel=models.CharField(max_length=12)
    email=models.EmailField()

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    codigo = models.CharField(max_length=50, unique=True)
    precio_venta = models.DecimalField(max_digits=10, decimal_places=2)
    codigo_barras = models.CharField(max_length=50, default=uuid.uuid4().hex)

    
    def __str__(self):
        return self.nombre

class TipoMovimiento(models.Model):
    numero = models.CharField(max_length=10, unique=True)
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Deposito(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=200)
    productos = models.ManyToManyField(Producto, through='StockDeposito')

    def __str__(self):
        return self.nombre
    
class StockDeposito(models.Model):
    deposito = models.ForeignKey(Deposito, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()

    def __str__(self):
        return f'{self.producto.nombre} en {self.deposito.nombre}'
    
class MovimientoStock(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    tipo = models.CharField(max_length=10, choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')])
    fecha = models.DateTimeField(auto_now_add=True)
    deposito = models.ForeignKey(Deposito, on_delete=models.CASCADE)
    tipo_movimiento = models.ForeignKey(TipoMovimiento, on_delete=models.CASCADE)  # Cambia el campo a ForeignKey


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='', null=True, blank=True)


    def __str__(self):
        return self.user.username

AppCoder/views.py
from django.shortcuts import *
from django.http import HttpResponse
from .forms import *
from AppCoder.models import *
from django.contrib.auth import *
import os
import barcode
from barcode.writer import ImageWriter
from django.views.decorators.http import *
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.views.generic import View, UpdateView
from .models import UserProfile
from .forms import UserProfileForm
from django.views import View
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from .forms import FormularioProductoPersonalizado
from .models import Producto

class UserProfileCreateView(View):
    template_name = 'AppCoder/crear_perfil.html'

    def get(self, request, *args, **kwargs):
        # Verificar si el perfil de usuario ya existe
        if UserProfile.objects.filter(user=request.user).exists():
            # Redirigir al usuario a la página de detalle de perfil o donde sea necesario
            return redirect(reverse('detalle_perfil', args=[request.user.id]))

        # Agregar el formulario al contexto
        form1 = UserProfileForm()
        return render(request, self.template_name, {'form1': form1})

    def post(self, request, *args, **kwargs):
        # Verificar si el perfil de usuario ya existe
        if UserProfile.objects.filter(user=request.user).exists():
            # Redirigir al usuario a la página de detalle de perfil o donde sea necesario
            return redirect(reverse('detalle_perfil', args=[request.user.id]))

        form1 = UserProfileForm(request.POST, request.FILES)
        if form1.is_valid():
            # Configurar el usuario asociado al perfil de usuario
            form1.instance.user = request.user
            form1.save()  # Guardar el perfil de usuario
            # Configura la URL de éxito después de guardar el perfil
            success_url = reverse('detalle_perfil', args=[request.user.id])
            return redirect(success_url)
        else:
            # Realizar acciones si el formulario no es válido
            return render(request, self.template_name, {'form1': form1})
        
def detalle_perfil(request, user_id):
    # Obtener el perfil del usuario o mostrar un error 404 si no existe
    user = get_object_or_404(User, id=user_id)
    perfil = UserProfile.objects.get(user=user)

    # Luego, pasa 'perfil' a tu plantilla para mostrar la información del perfil
    return render(request, 'AppCoder/detalle_perfil.html', {'perfil': perfil})
 

def custom_logout(request):
    logout(request)
    return render(request, 'AppCoder/logout.html')

def inicio(request):

    return render(request,"AppCoder/inicio.html")



def cliente(request):
    clientes = Cliente.objects.all()

    # Obtén el valor de búsqueda desde la consulta GET
    search_query = request.GET.get('search')
    if search_query:
        # Filtra los clientes por nombre si se proporciona una consulta de búsqueda
        clientes = clientes.filter(nombre__icontains=search_query)

    return render(request, 'AppCoder/cliente.html', {'clientes': clientes})




def formProducto(request):
    if request.method == "POST":
        formulario = FormularioProductoPersonalizado(request.POST)
        if formulario.is_valid():
            datos_producto = formulario.cleaned_data

            # Verifica si el código ya existe en la base de datos
            if Producto.objects.filter(codigo=datos_producto["codigo"]).exists():
                formulario.add_error("codigo", "Este código ya está en uso.")
            else:
                # Crea una instancia del producto y guárdala en la base de datos
                producto = Producto(
                    nombre=datos_producto["nombre"],
                    codigo=datos_producto["codigo"],
                    precio_venta=datos_producto["precio_venta"]
                )
                producto.save()

                return redirect("detalle_producto", producto_id=producto.id)
    else:
        formulario = FormularioProductoPersonalizado()

    return render(request, "AppCoder/formProducto.html", {"form1": formulario})


def eliminar_producto(request, producto_id):
    # Obtiene el producto específico según su ID o muestra un error 404 si no existe
    producto = get_object_or_404(Producto, pk=producto_id)

    if request.method == 'POST':
        # Si se envió una solicitud POST, elimina el producto
        producto.delete()
        return redirect('lista_productos')  # Redirige a la página de lista de productos después de eliminar

    # Si la solicitud no es POST (por ejemplo, GET), muestra una confirmación de eliminación
    return render(request, 'AppCoder/eliminar_producto.html', {'producto': producto})


def lista_productos(request):
    # Obtén el valor de búsqueda desde la URL
    search_query = request.GET.get('search', '')

    # Filtra los productos que coincidan con la búsqueda
    productos = Producto.objects.filter(nombre__icontains=search_query)

    return render(request, 'AppCoder/lista_productos.html', {'productos': productos, 'search_query': search_query})


def editar_producto(request, producto_id):
    # Obtén el producto específico según su ID o muestra un error 404 si no existe
    producto = get_object_or_404(Producto, pk=producto_id)

    if request.method == "POST":
        formulario = FormularioEditarProducto(request.POST, instance=producto)
        if formulario.is_valid():
            formulario.save()
            return redirect("detalle_producto", producto_id=producto.id)
    else:
        formulario = FormularioEditarProducto(instance=producto)

    return render(request, "AppCoder/editar_producto.html", {"formulario": formulario, "producto": producto})


def detalle_producto(request, producto_id):
    # Obtiene el producto específico según su ID o muestra un error 404 si no existe
    producto = get_object_or_404(Producto, pk=producto_id)
    
    return render(request, 'AppCoder/detalle_producto.html', {'producto': producto})


def generar_codigo_de_barras(producto):
    # Ruta donde deseas almacenar las imágenes de códigos de barras
    directorio_imagenes = 'path/C:/PONUS/ProductoIMG/'

    # Verificar si el directorio existe, y si no, crearlo
    if not os.path.exists(directorio_imagenes):
        os.makedirs(directorio_imagenes)

    # Crear un objeto de código de barras (por ejemplo, EAN-13)
    codigo = barcode.get_barcode_class('ean13')

    # Generar el código de barras con el valor del campo 'codigo_barras' del producto
    codigo_generado = codigo(producto.codigo_barras, writer=ImageWriter(), add_checksum=False)

    # Construir la ruta completa para la imagen del código de barras
    ruta_imagen = os.path.join(directorio_imagenes, f'{producto.codigo_barras}.png')

    # Guardar la imagen del código de barras en la ruta
    codigo_generado.save(ruta_imagen)

    return ruta_imagen



def lista_tipos_movimiento(request):
    tipos_movimiento = TipoMovimiento.objects.all()
    return render(request, 'lista_tipos_movimiento.html', {'tipos_movimiento': tipos_movimiento})

def crear_tipo_movimiento(request):
    if request.method == 'POST':
        form = TipoMovimientoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lista_tipos_movimiento')
    else:
        form = TipoMovimientoForm()
    return render(request, 'crear_tipo_movimiento.html', {'form': form})

# Vistas para Movimientos de Stock

def lista_movimientos_stock(request):
    # Obtén todos los movimientos de stock
    movimientos_stock = MovimientoStock.objects.all()

    return render(request, 'AppCoder/lista_movimientos_stock.html', {'movimientos_stock': movimientos_stock})

from .models import Producto  # Asegúrate de importar el modelo Producto

def crear_movimiento_stock(request):
    if request.method == 'POST':
        formulario = FormularioMovimientoStock(request.POST)
        if formulario.is_valid():
            movimiento_stock = formulario.save()
            return redirect('lista_movimientos_stock')
    else:
        formulario = FormularioMovimientoStock()
    
    # Obtén la lista de productos y pásala al contexto
    productos = Producto.objects.all()  # Esto obtendrá todos los productos en la base de datos

    return render(request, 'AppCoder/crear_movimiento_stock.html', {'formulario': formulario, 'productos': productos})

def editar_movimiento_stock(request, movimiento_stock_id):
    # Obtén el movimiento de stock específico según su ID o muestra un error 404 si no existe
    movimiento_stock = get_object_or_404(MovimientoStock, pk=movimiento_stock_id)

    if request.method == "POST":
        # Si se envió una solicitud POST, procesa el formulario
        formulario = MovimientoStockForm(request.POST, instance=movimiento_stock)
        if formulario.is_valid():
            formulario.save()
            return redirect('detalle_movimiento_stock', movimiento_stock_id=movimiento_stock.id)
    else:
        # Si la solicitud no es POST, muestra el formulario de edición
        formulario = MovimientoStockForm(instance=movimiento_stock)

    return render(request, 'AppCoder/editar_movimiento_stock.html', {'formulario': formulario, 'movimiento_stock': movimiento_stock})


def detalle_movimiento_stock(request, movimiento_stock_id):
    # Obtiene el movimiento de stock específico según su ID o muestra un error 404 si no existe
    movimiento_stock = get_object_or_404(MovimientoStock, pk=movimiento_stock_id)

    if request.method == 'POST':
        # Si se envió una solicitud POST, elimina el movimiento de stock
        movimiento_stock.delete()

AppCoder/templates/AppCoder/cliente.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
           
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'AppCoder/assets/favicon.ico' %}" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'AppCoder/css/styles.css' %}" rel="stylesheet" />
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{% url 'inicio' %}">Inicio</a>
        </div>
    </nav>


    </header>
    <!-- Client List Section -->
    <section class="page-section portfolio" id="client-list">
        <div class="container">
            <!-- Client List Section Heading -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="divider-custom">
                        <div class="divider-custom-line"></div>
                        <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                        <div class="divider-custom-line"></div>
                    </div>
                    <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Lista de Clientes</h2>
                    <!-- Icon Divider -->
                    <div class="divider-custom">
                        <div class="divider-custom-line"></div>
                        <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                        <div class="divider-custom-line"></div>
                    </div>
                </div>
            </div>
            <!-- Formulario de búsqueda por nombre de cliente -->
        <form method="GET" class="mb-4">
            <div class="input-group">
                <input type="text" name="search" class="form-control" placeholder="Buscar por nombre de cliente" value="{{ search_query }}" />
                <div class="input-group-append">
                    <button type="submit" class="btn btn-primary">Buscar</button>
                </div>
            </div>
         </form>
            <!-- Botón para Ver Todos Cliente -->
            <a href="{% url 'lista_clientes' %}" class="btn btn-secondary">Ver Todos</a>
            
            <!-- Botón para agregar Cliente -->
            <a href="{% url 'formCliente' %}" class="btn btn-success">Agregar Cliente</a>
        {% if clientes %}
            <!-- Client Table -->
            <table class="table table-bordered">
                <thead class="bg-primary text-white">
                    <tr>
                        <th>Nombre</th>
                        <th>Correo Electrónico</th>
                        <th>Numero Celular</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cliente in clientes %}
                        <tr>
                            <td>{{ cliente.nombre }}</td>
                            <td>{{ cliente.email }}</td>
                            <td>{{ cliente.cel }}</td>
                            <td>
                                <!-- Botón para ver detalles del cliente -->
                                <a href="{% url 'detalle_cliente' cliente.id %}" class="btn btn-info btn-sm">Detalles</a>
                                <a href="{% url 'editar_cliente' cliente.id %}" class="btn btn-warning btn-sm">Editar</a>
                                <a href="{% url 'eliminar_cliente' cliente.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
        <p>No se encontraron resultados.</p>
        {% endif %}
        </div>
    </section>
    <!-- Footer -->
    <footer class="footer text-center">
        <div class="container">
            <!-- Footer content -->
        </div>
    </footer>
    <!-- Copyright Section -->
    <div class="copyright py-4 text-center text-white">
        <div class="container"><small>Dante Turcutto - Final</small></div>
    </div>
    <!-- Bootstrap core JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS -->
    <script src="{% static 'AppCoder/js/scripts.js' %}"></script>
    <!-- SB Forms JS -->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
</html>

AppCoder/templates/AppCoder/crear_tipo_movimiento.html
{% extends "base.html" %}

{% block content %}
  <h2>Agregar Tipo de Movimiento</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
  </form>
  <a href="{% url 'lista_tipos_movimiento' %}">Volver a la Lista</a>
{% endblock %}

AppCoder/templates/AppCoder/inicio.html
{% extends "AppCoder/padre.html" %}

{% load static %}

{% block titulo %}
Bienvenido, {{ user.username }}
{% endblock %}

{% block descripcion %} 
{% endblock %}

AppCoder/templates/AppCoder/lista_movimientos_stock.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'AppCoder/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'AppCoder/css/styles.css' %}" rel="stylesheet" />
        <!-- Agrega el enlace al archivo de estilos CSS aquí -->
        <link href="{% static 'AppCoder/css/menu-styles.css' %}" rel="stylesheet" type="text/css" />

    </head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{% url 'inicio' %}">Inicio</a>
        </div>
    </nav>

    <!-- Movimientos de Stock Section -->
    <section class="page-section portfolio" id="movimientos-stock">
        <div class="container">
            <!-- Movimientos de Stock Section Heading -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="divider-custom">
                        <div class="divider-custom-line"></div>
                        <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                        <div class="divider-custom-line"></div>
                    </div>
                    <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Movimientos de Stock</h2>
                    <!-- Icon Divider -->
                    <div class="divider-custom">
                        <div class="divider-custom-line"></div>
                        <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                        <div class="divider-custom-line"></div>
                    </div>
                </div>
            
            </div>
            <div class="menu">
                <ul> 
                    <li><a href="{% url 'crear_deposito' %}">Crear Depósito</a></li>
                    <li><a href="{% url 'crear_tipo_movimiento' %}">Crear Tipo de Movimiento</a></li>
                    <li><a href="{% url 'crear_movimiento_stock' %}">Crear Movimiento de Stock</a></li>
                </ul>
            </div>
           

            <!-- Formulario de búsqueda por producto -->
            <form method="GET" class="mb-4">
                <div class="input-group">
                    <input type="text" name="search" class="form-control" placeholder="Buscar por producto" />
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary">Buscar</button>
                    </div>
                </div>
            </form>

            <!-- Botón para Ver Todos los movimientos de stock -->
            <a href="{% url 'lista_movimientos_stock' %}" class="btn btn-secondary">Ver Todos</a>

            <!-- Botón para agregar movimiento de stock
             <a href="{% url 'crear_movimiento_stock' %}" class="btn btn-success">Agregar Movimiento de Stock</a> -->
            

            {% if movimientos %}
                <!-- Movimientos de Stock Table -->
                <table class="table table-bordered">
                    <thead class="bg-primary text-white">
                        <tr>
                            <th>Producto</th>
                            <th>Tipo de Movimiento</th>
                            <th>Cantidad</th>
                            <th>Depósito</th>
                            <th>Fecha</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for movimiento in movimientos %}
                            <tr>
                                <td>{{ movimiento.producto }}</td>
                                <td>{{ movimiento.get_tipo_movimiento_display }}</td>
                                <td>{{ movimiento.cantidad }}</td>
                                <td>{{ movimiento.deposito }}</td>
                                <td>{{ movimiento.fecha }}</td>
                                <td>
                                    <!-- Botón para editar movimiento de stock -->
                                    <a href="{% url 'editar_movimiento_stock' movimiento.id %}" class="btn btn-warning btn-sm">Editar</a>
                                    <!-- Botón para eliminar movimiento de stock -->
                                    <a href="{% url 'eliminar_movimiento_stock' movimiento.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No se encontraron resultados.</p>
            {% endif %}
        </div>
    </section>

    <!-- Footer -->
    <footer class="footer text-center">
        <div class="container">
            <!-- Footer content -->
        </div>
    </footer>

    <!-- Copyright Section -->
    <div class="copyright py-4 text-center text-white">
        <div class="container"><small>Dante Turcutto - Final</small></div>
    </div>

    <!-- Bootstrap core JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS -->
    <script src="{% static 'AppCoder/js/scripts.js' %}"></script>
    <!-- SB Forms JS -->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
</html>

AppCoder/templates/AppCoder/registro_usuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
  
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Registro de Usuario</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'AppCoder/assets/favicon.ico' %}" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'AppCoder/css/styles.css' %}" rel="stylesheet" />
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{% url 'inicio' %}">Inicio</a>
        </div>
    </nav>
    <!-- Registro de Usuario Section -->
    <section class="page-section" id="registro-usuario">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h2 class="text-center text-uppercase text-secondary">Registro de Usuario</h2>
                    <form method="post" class="formulario" enctype="multipart/form-data"> <!-- Agregamos enctype para subir archivos -->
                        {% csrf_token %}
                        {{ form.as_p }}
                        <label for="id_avatar">Avatar:</label>
                        <input type="file" id="id_avatar" name="avatar">
                        <div class="text-center">
                            <button type="submit" class="btn btn-success">Registrarse</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Footer -->
    <footer class="footer text-center">
        <div class="container">
            <!-- Footer content -->
        </div>
    </footer>
    <!-- Copyright Section -->
    <div class="copyright py-4 text-center text-white">
        <div class="container"><small>Dante Turcutto - Final</small></div>
    </div>
    <!-- Bootstrap core JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS -->
    <script src="{% static 'AppCoder/js/scripts.js' %}"></script>
    <!-- SB Forms JS -->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
</html>